package com.github.deckyfx.httprequest.dao;

import com.github.deckyfx.greendao.AbstractDao;
import com.github.deckyfx.greendao.AbstractDaoSession;
import com.github.deckyfx.greendao.database.Database;
import com.github.deckyfx.greendao.identityscope.IdentityScopeType;
import com.github.deckyfx.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see com.github.deckyfx.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig requestCacheDaoConfig;

    private final RequestCacheDao requestCacheDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        requestCacheDaoConfig = daoConfigMap.get(RequestCacheDao.class).clone();
        requestCacheDaoConfig.initIdentityScope(type);

        requestCacheDao = new RequestCacheDao(requestCacheDaoConfig, this);

        registerDao(RequestCache.class, requestCacheDao);
    }
    
    public void clear() {
        requestCacheDaoConfig.clearIdentityScope();
    }

    public RequestCacheDao getRequestCacheDao() {
        return requestCacheDao;
    }

}
